### ISSUE TITLE
Error during running of example.py

### ISSUE THREAD

**Issue by dshortmn** [cyrils/renogy-bt1#10]
Traceback (most recent call last):
  File "c:\GitHub\renogy-bt1\example.py", line 25, in <module>
    BTOneClient(config, on_data_received).connect()
  File "c:\GitHub\renogy-bt1\renogybt\BTOneClient.py", line 36, in connect
    self.manager = DeviceManager(adapter_name=self.config['device']['adapter'], mac_address=self.config['device']['mac_addr'], alias=self.config['device']['alias'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\GitHub\renogy-bt1\renogybt\BLE.py", line 9, in __init__
    super(). __init__(adapter_name, mac_address, alias)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by cyrils** [comment]
Hello, the `gatt` library used for BLE communication is not supported in Windows/Mac platform, please try in a Linux environment (ex: Raspberry Pi)
