### ISSUE TITLE
negative sensor temperature

### ISSUE THREAD

**Issue by Byter09** [cyrils/renogy-bt1#4]
Hello!

First of, I would like to thank you for this project. I use it to send off data updates to InfluxDB and Home Assistant :)

Now, to the problem. Its getting quite cold, and the temperature at the battery probe went below 0°C.

It's unclear whether this is the Rover 20a having a problem, or how the data is retrieved. Just to make sure I'm opening this ticket. I checked both InfluxDB and Home Assistant and they both report the same value. I then went ahead and checked the webhook I use to receive the data I'm sending with your neat project, and my code doesn't seem to change any negative values (I sent mock data to check and it works perfectly), so that leaves me to believe it might be a bug in your code. If I knew more about python I'd have a look but it's not really my forte haha.

The resulting graph from last night looks like this haha
![grafik](https://user-images.githubusercontent.com/16060697/207838650-0a6f0169-0b65-411e-8d96-0c20c65e542b.png)

It went up to 129°C, which looks like an underflow to me.

If you need any more information, I'm happy to help out with whatever you need.

EDIT: Here's the raw data: It goes from 0 directly to 129°C.
![grafik](https://user-images.githubusercontent.com/16060697/207855667-c0db4586-d669-41ac-a12c-820a7a0be019.png)

**Comment by cyrils** [comment]
Could be problem with hex parsing, I'll look into it later tonight.

**Comment by cyrils** [comment]
@Byter09 I've updated the code, can you check it out? According to documentation 7th bit it for sign, which I've been ignoring. Only change is in `Utils.py`.

**Comment by Byter09** [comment]
I have updated my docker container and I guess we'll see if it works. But thank you for taking the time. If you want me I can put some ice cubes on it haha :D
